#!/bin/bash

set -e
. /usr/share/debconf/confmodule


RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

#==================================================================================
mysql_password() 
#==================================================================================
{
    # Получаем пароль от MySQL
    string=$(sudo cat /etc/mysql/debian.cnf)
    regsubstring="password"
    passwd="${string#*password}"
    passwd="${passwd%%socket*}"
    len="$((${#passwd}-4))"
    passwd="${passwd:3:$len}"
    echo $passwd
}


#echo "${RED}postinst $1${RESET}"

case "$1" in
#================================================================================
configure)
#==================================================================================

    export MYSQL_PWD=$(mysql_password)
    db_get tegia/mysql-username
    MYSQL_USERNAME="$RET"
    db_get tegia/mysql-password
    MYSQL_PASSWORD="$RET"
    mysql -u  debian-sys-maint -e "CREATE USER '$MYSQL_USERNAME'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';"
    mysql -u  debian-sys-maint -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USERNAME'@'localhost';"
    mysql -u  debian-sys-maint -e "FLUSH PRIVILEGES;"
    mysql -u  debian-sys-maint -e "CREATE DATABASE IF NOT EXISTS tegia_core DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
    db_unregister tegia/mysql-password


    chmod -R 777 /var/log/tegia/
    echo "${GREEN}tegia-node-bin install success${RESET}" 
;;
#==================================================================================
upgrade)
#==================================================================================

    echo "${GREEN}upgrade success${RESET}" 

;;
#==================================================================================
abort-upgrade|abort-remove|abort-deconfigure)
#==================================================================================


;;
#==================================================================================
*)
#==================================================================================
    echo "postinst called with unknown argument \`$1'" >&2
    exit 0
;;
esac


exit 0

