#!/bin/bash

# set -e
. /usr/share/debconf/confmodule

RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

#==================================================================================
mysql_password() 
#==================================================================================
{
    # Получаем пароль от MySQL
    string=$(sudo cat /etc/mysql/debian.cnf)
    regsubstring="password"
    passwd="${string#*password}"
    passwd="${passwd%%socket*}"
    len="$((${#passwd}-4))"
    passwd="${passwd:3:$len}"
    echo $passwd
}


case "$1" in
#================================================================================
remove)
#================================================================================

    export MYSQL_PWD=$(mysql_password)
    db_get tegia/mysql-username
    MYSQL_USERNAME="$RET"

    mysql -u  debian-sys-maint -e "DROP DATABASE tegia_core;"
    mysql -u  debian-sys-maint -e "DROP USER IF EXISTS '$MYSQL_USERNAME'@'localhost';"
    
;;
#================================================================================
purge)
#================================================================================

    db_unregister tegia/setup-mode   
    db_unregister tegia/mysql-username
 
;;
#================================================================================
upgrade)
#================================================================================

    

;;
#================================================================================
abort-upgrade|abort-remove|abort-deconfigure)
#================================================================================


;;
#================================================================================
*)
#================================================================================
    echo "postrm called with unknown argument \`$1'" >&2
    exit 0
;;
esac


exit 0




