#!/bin/bash

set -e
. /usr/share/debconf/confmodule


RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`


case "$1" in
#==================================================================================
configure)
#==================================================================================

#	Настраиваем G++
	update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

# Настраиваем директории
  cd /home/$SUDO_USER
  mkdir -p tegia
  mkdir -p tegia/vendors
  mkdir -p tegia/configurations
  mkdir -p tegia/nodes
  mkdir -p tegia/debs
  mkdir -p tegia/ui

# Настраиваем используемые библиотеки

  # -------------------------------------------------------------- 
  # Jsoncpp
  # -------------------------------------------------------------- 
	cd tegia/vendors
	git clone https://github.com/open-source-parsers/jsoncpp.git
 	cd jsoncpp
	python amalgamate.py

  # -------------------------------------------------------------- 
  # Gumbo parser
  # -------------------------------------------------------------- 
  cd ../
	git clone https://github.com/google/gumbo-parser.git
	cd gumbo-parser 
	./autogen.sh
	./configure
	make
	sudo make install

  # -------------------------------------------------------------- 
  # xml2json
  # -------------------------------------------------------------- 
  cd ../
	git clone https://github.com/Cheedoong/xml2json
  sudo ln -s /home/$SUDO_USER/tegia/vendors/xml2json /usr/include/xml2json

  # -------------------------------------------------------------- 
  # nlohmann json
  # -------------------------------------------------------------- 
  mkdir nlohmann
  cd nlohmann
  wget https://github.com/nlohmann/json/releases/download/v3.7.3/include.zip
  unzip include.zip
  sudo ln -s /home/$SUDO_USER/tegia/vendors/nlohmann/single_include/nlohmann /usr/include/nlohmann



  chown $SUDO_USER:$SUDO_USER -R /home/$SUDO_USER/tegia

	echo "${GREEN}tegia-devtools install success${RESET}" 
;;
#==================================================================================
upgrade)
#==================================================================================
    
	echo "${GREEN}tegia-devtools upgrade success${RESET}" 
;;
#==================================================================================
abort-upgrade|abort-remove|abort-deconfigure)
#==================================================================================


;;
#==================================================================================
*)
#==================================================================================
    echo "tegia-devtools postinst called with unknown argument \`$1'" >&2
    exit 0
;;
esac


exit 0

