#!/bin/bash

set -e
. /usr/share/debconf/confmodule

RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

#==================================================================================
mysql_password() 
#==================================================================================
{
    # Получаем пароль от MySQL
    string=$(sudo cat /etc/mysql/debian.cnf)
    regsubstring="password"
    passwd="${string#*password}"
    passwd="${passwd%%socket*}"
    len="$((${#passwd}-4))"
    passwd="${passwd:3:$len}"
    echo $passwd
}
export -f mysql_password

#==================================================================================
git_clone()
#==================================================================================
{
    param=true
    while [ param ]
    do
        RESULT=$(git clone "$1" "$2" 2>&1 || true)
    
        echo " "
        echo $RESULT

        if [ -d "$2" ]
           then
              break
           else
              echo "${RED}[!] Репозиторий не выгружен. Повторите ввод логина и пароля${RESET}"   
              echo " "
        fi

    done 
    chown $SUDO_USER:$SUDO_USER -R $2
    echo "${GREEN}[!] Репозиторий выгружен${RESET}" 
}


echo "${RED}postinst $1${RESET}"

case "$1" in
#==================================================================================
configure)
#==================================================================================
    # Шаг 1: Выгружаем и настраиваем репозиторий 
    # -----------------------------------------------------------------------------------------------------

    cd /var/tegia
    git_clone "https://gitlab.com/tegia-acm/tegia-node.git" "/var/tegia/platform"
    ln -s /var/tegia/platform/include /usr/include/tegia
    # Шаг 2: Заливаем БД
    # -----------------------------------------------------------------------------------------------------
    export MYSQL_PWD=$(mysql_password)
    db_get tegia/mysql-username
    MYSQL_USERNAME="$RET"
    db_get tegia/mysql-password
    MYSQL_PASSWORD="$RET"
    mysql -u  debian-sys-maint -e "CREATE USER '$MYSQL_USERNAME'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';"
    mysql -u  debian-sys-maint -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USERNAME'@'localhost';"
    mysql -u  debian-sys-maint -e "FLUSH PRIVILEGES;"
    mysql -u  debian-sys-maint -e "CREATE DATABASE IF NOT EXISTS tegia_core DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
    db_unregister tegia/mysql-password

    # Шаг 3: Устанавливаем библиотеки
    # -----------------------------------------------------------------------------------------------------
    cd /var/tegia/platform/src/vendors/
    git clone https://github.com/open-source-parsers/jsoncpp.git
    cd jsoncpp
    python amalgamate.py

    cd /var/tegia/platform/src/vendors/
    git clone https://github.com/google/gumbo-parser.git
    cd gumbo-parser 
    ./autogen.sh
    ./configure
    make
    sudo make install

    cd /var/tegia/platform/src/vendors/
    git clone https://github.com/Cheedoong/xml2json
    
    # Шаг 4: Настраиваем Платформу
    # -----------------------------------------------------------------------------------------------------
    cp /var/tegia/platform/_bin/configs/config.example.json /var/tegia/platform/_bin/config.json
    cd /var/tegia/platform/_bin
    mkdir tmp
    make tegia-node
    make tegia-config

    # Шаг 5: собираем акутальную документацию
    cd /var/tegia/platform/docs
    doxygen doxygen.cfg 


    chown $SUDO_USER:$SUDO_USER -R /var/tegia/ 
    echo "${GREEN}success install${RESET}" 
;;
#==================================================================================
upgrade)
#==================================================================================

;;
#==================================================================================
abort-upgrade|abort-remove|abort-deconfigure)
#==================================================================================

;;
#==================================================================================
*)
#==================================================================================
    echo "postinst called with unknown argument \`$1'" >&2
    exit 0
;;
esac


exit 0







