name: Build Docs

on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Установка пакета @diplodoc/cli
        run: npm i @diplodoc/cli -g
        shell: bash

      - name: Сборка документации
        run: yfm -i ./docs -o ./docs-html
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v5
